extends Node
## RoadGraph (autoload): the road network as data, loaded from
## Map/road_graph.json (generated by tools/build_road_graph.py).
##
## Every road segment between two intersections is an "edge" with an integer
## id. World (truth) and Knowledge (what the player knows) both store their
## per-road state against these edge ids.

# AI-assisted (Claude Opus 5.5). Prompt used:
#   "Write a Godot 4.7 GDScript autoload called RoadGraph that loads
#    res://Map/road_graph.json (nodes = intersection positions, edges = road
#    segments with endpoint node ids 'a'/'b', road width class 'w', pixel
#    length 'len' and full polyline 'pts', all in the Camberwell chunk's pixel
#    frame). It must:
#      - Build an AStar2D over the intersections whose step cost is the real
#        polyline length of the road between them (not straight-line distance).
#      - Snap any world position to the closest point ON a road (not just the
#        closest intersection), using a uniform spatial grid of polyline
#        segments so it is cheap enough to call every frame for route preview.
#      - Return a route between two snapped road positions as both a
#        polyline that follows the road geometry exactly and the ordered list
#        of edge ids it travels, so crews can report which roads they drove.
#        Handle start and end lying part-way along an edge, including both
#        on the same edge.
#      - Expose small helpers (edge count, edge points, edge midpoint, width
#        class) for the map overlay to draw from.
#    Keep it self-contained, typed, and commented for second-year students."

const GRAPH_PATH := "res://Map/road_graph.json"
const GRID_CELL := 96.0

## A position on the road network: which edge, how far along it from end
## 'a' (in pixels), and the resulting world point.
class RoadPos:
	var edge: int
	var dist: float
	var point: Vector2
	func _init(e: int, d: float, p: Vector2) -> void:
		edge = e
		dist = d
		point = p

## A route along roads: the polyline to follow and the edges it covers.
class Route:
	var points := PackedVector2Array()
	var point_edges := PackedInt32Array()   # edge each point lies on
	var edges: Array[int] = []
	var length := 0.0

	func add(pts: PackedVector2Array, edge: int) -> void:
		points.append_array(pts)
		for i in pts.size():
			point_edges.append(edge)
		if edges.is_empty() or edges.back() != edge:
			edges.append(edge)


# AStar2D whose step cost is the real road length between two intersections.
class RoadAStar extends AStar2D:
	var graph: Node
	func _compute_cost(from_id: int, to_id: int) -> float:
		return graph.edge_length(graph.edge_between(from_id, to_id))
	func _estimate_cost(from_id: int, to_id: int) -> float:
		return get_point_position(from_id).distance_to(get_point_position(to_id))


var node_positions := PackedVector2Array()
var edge_a := PackedInt32Array()
var edge_b := PackedInt32Array()
var edge_width := PackedFloat32Array()
var edge_len := PackedFloat32Array()
var edge_pts: Array[PackedVector2Array] = []
var edge_cum: Array[PackedFloat32Array] = []   # cumulative length at each point

var _pair_to_edge := {}                        # Vector2i(a, b) -> edge id
var _grid := {}                                # Vector2i cell -> [edge, seg, ...]
var _astar := RoadAStar.new()


func _ready() -> void:
	_load()


func _load() -> void:
	var file := FileAccess.open(GRAPH_PATH, FileAccess.READ)
	if file == null:
		push_error("RoadGraph: could not open %s" % GRAPH_PATH)
		return
	var data: Dictionary = JSON.parse_string(file.get_as_text())

	_astar.graph = self
	for i in data["nodes"].size():
		var n: Array = data["nodes"][i]
		var p := Vector2(n[0], n[1])
		node_positions.append(p)
		_astar.add_point(i, p)

	for e: Dictionary in data["edges"]:
		var id := edge_a.size()
		var a := int(e["a"])
		var b := int(e["b"])
		var pts := PackedVector2Array()
		var cum := PackedFloat32Array()
		var total := 0.0
		for raw: Array in e["pts"]:
			var p := Vector2(raw[0], raw[1])
			if pts.size() > 0:
				total += pts[pts.size() - 1].distance_to(p)
			pts.append(p)
			cum.append(total)
		edge_a.append(a)
		edge_b.append(b)
		edge_width.append(float(e["w"]))
		edge_len.append(total)
		edge_pts.append(pts)
		edge_cum.append(cum)

		# Keep the shortest edge if two roads join the same pair of nodes.
		var key := Vector2i(mini(a, b), maxi(a, b))
		if not _pair_to_edge.has(key) or total < edge_len[_pair_to_edge[key]]:
			_pair_to_edge[key] = id
		if a != b and not _astar.are_points_connected(a, b):
			_astar.connect_points(a, b)

		for s in pts.size() - 1:
			for cell in _cells_for_segment(pts[s], pts[s + 1]):
				if not _grid.has(cell):
					_grid[cell] = PackedInt32Array()
				_grid[cell].append(id)
				_grid[cell].append(s)

	print("RoadGraph: %d intersections, %d road segments" % [node_positions.size(), edge_a.size()])


# --- Queries ---------------------------------------------------------------

func edge_count() -> int:
	return edge_a.size()

func edge_length(edge: int) -> float:
	return edge_len[edge] if edge >= 0 else INF

func edge_between(a: int, b: int) -> int:
	return _pair_to_edge.get(Vector2i(mini(a, b), maxi(a, b)), -1)

func edge_midpoint(edge: int) -> Vector2:
	return point_at(edge, edge_len[edge] * 0.5)

## Road class from the OSM stroke width: 0 = local street, 1 = collector,
## 2 = main road. Useful for speeds and traffic odds.
func edge_class(edge: int) -> int:
	var w := edge_width[edge]
	if w >= 17.0:
		return 2
	if w >= 11.0:
		return 1
	return 0


## World point a given distance along an edge, measured from end 'a'.
func point_at(edge: int, dist: float) -> Vector2:
	var pts := edge_pts[edge]
	var cum := edge_cum[edge]
	dist = clampf(dist, 0.0, edge_len[edge])
	for i in range(1, pts.size()):
		if cum[i] >= dist:
			var seg := cum[i] - cum[i - 1]
			var t := 0.0 if seg <= 0.0 else (dist - cum[i - 1]) / seg
			return pts[i - 1].lerp(pts[i], t)
	return pts[pts.size() - 1]


## Closest point on any road to a world position. Returns null if no road is
## within max_radius pixels.
func snap(world_pos: Vector2, max_radius := 400.0) -> RoadPos:
	var best: RoadPos = null
	var best_d2 := max_radius * max_radius
	var c := _cell(world_pos)
	var ring := 0
	var max_ring := int(ceil(max_radius / GRID_CELL))
	var checked := {}
	while ring <= max_ring:
		for x in range(c.x - ring, c.x + ring + 1):
			for y in range(c.y - ring, c.y + ring + 1):
				if maxi(absi(x - c.x), absi(y - c.y)) != ring:
					continue  # only the outer ring is new
				var list: PackedInt32Array = _grid.get(Vector2i(x, y), PackedInt32Array())
				for i in range(0, list.size(), 2):
					var e := list[i]
					var s := list[i + 1]
					var k := e * 4096 + s
					if checked.has(k):
						continue
					checked[k] = true
					var a := edge_pts[e][s]
					var b := edge_pts[e][s + 1]
					var p := Geometry2D.get_closest_point_to_segment(world_pos, a, b)
					var d2 := p.distance_squared_to(world_pos)
					if d2 < best_d2:
						best_d2 = d2
						best = RoadPos.new(e, edge_cum[e][s] + a.distance_to(p), p)
		# Anything further out than this ring can't beat the current best.
		if best != null and sqrt(best_d2) < ring * GRID_CELL:
			break
		ring += 1
	return best


## Shortest route along roads between two snapped positions.
func route(from: RoadPos, to: RoadPos) -> Route:
	var r := Route.new()
	if from == null or to == null:
		return r

	if from.edge == to.edge:
		r.add(_sub_points(from.edge, from.dist, to.dist), from.edge)
		r.length = absf(to.dist - from.dist)
		return r

	# Try leaving 'from' by either end and entering 'to' by either end.
	var best_cost := INF
	var best_path := PackedInt64Array()
	var best_from_end := 0
	var best_to_end := 0
	for from_end in [edge_a[from.edge], edge_b[from.edge]]:
		var lead := from.dist if from_end == edge_a[from.edge] else edge_len[from.edge] - from.dist
		for to_end in [edge_a[to.edge], edge_b[to.edge]]:
			var tail := to.dist if to_end == edge_a[to.edge] else edge_len[to.edge] - to.dist
			var path := _astar.get_id_path(from_end, to_end)
			if path.is_empty():
				continue
			var cost := lead + tail + _path_length(path)
			if cost < best_cost:
				best_cost = cost
				best_path = path
				best_from_end = from_end
				best_to_end = to_end

	if best_path.is_empty():
		return r

	r.length = best_cost
	var from_end_dist := 0.0 if best_from_end == edge_a[from.edge] else edge_len[from.edge]
	r.add(_sub_points(from.edge, from.dist, from_end_dist), from.edge)
	for i in best_path.size() - 1:
		var e := edge_between(best_path[i], best_path[i + 1])
		var forward := edge_a[e] == best_path[i]
		r.add(_sub_points(e, 0.0 if forward else edge_len[e], edge_len[e] if forward else 0.0), e)
	var to_end_dist := 0.0 if best_to_end == edge_a[to.edge] else edge_len[to.edge]
	r.add(_sub_points(to.edge, to_end_dist, to.dist), to.edge)
	return r


# --- Internals -------------------------------------------------------------

func _path_length(path: PackedInt64Array) -> float:
	var total := 0.0
	for i in path.size() - 1:
		total += edge_length(edge_between(path[i], path[i + 1]))
	return total


## Polyline along an edge from distance d0 to d1 (either direction).
func _sub_points(edge: int, d0: float, d1: float) -> PackedVector2Array:
	var out := PackedVector2Array()
	var pts := edge_pts[edge]
	var cum := edge_cum[edge]
	out.append(point_at(edge, d0))
	if d1 >= d0:
		for i in pts.size():
			if cum[i] > d0 and cum[i] < d1:
				out.append(pts[i])
	else:
		for i in range(pts.size() - 1, -1, -1):
			if cum[i] < d0 and cum[i] > d1:
				out.append(pts[i])
	out.append(point_at(edge, d1))
	return out


func _cell(p: Vector2) -> Vector2i:
	return Vector2i(floori(p.x / GRID_CELL), floori(p.y / GRID_CELL))


func _cells_for_segment(a: Vector2, b: Vector2) -> Array[Vector2i]:
	var out: Array[Vector2i] = []
	var ca := _cell(a)
	var cb := _cell(b)
	for x in range(mini(ca.x, cb.x), maxi(ca.x, cb.x) + 1):
		for y in range(mini(ca.y, cb.y), maxi(ca.y, cb.y) + 1):
			out.append(Vector2i(x, y))
	return out
